"""
PlatformIO pre-build script: embed web UI files in firmware.

Reads all files from data/www/, gzips them, and generates a C header
(include/web_content.h) with PROGMEM byte arrays. The web server
serves these directly — no separate LittleFS upload needed for the UI.

Usage in platformio.ini:
    extra_scripts = pre:tools/embed_webui.py
"""

import os
import gzip
import hashlib
from pathlib import Path

Import("env")

WWW_DIR = os.path.join(env.subst("$PROJECT_DIR"), "data", "www")
OUTPUT_HEADER = os.path.join(env.subst("$PROJECT_DIR"), "include", "web_content.h")
HASH_FILE = os.path.join(env.subst("$PROJECT_DIR"), ".pio", "web_content.hash")

# MIME type mapping
MIME_TYPES = {
    ".html": "text/html",
    ".css": "text/css",
    ".js": "application/javascript",
    ".json": "application/json",
    ".svg": "image/svg+xml",
    ".png": "image/png",
    ".ico": "image/x-icon",
    ".woff": "font/woff",
    ".woff2": "font/woff2",
}


def get_mime_type(filepath):
    ext = os.path.splitext(filepath)[1].lower()
    return MIME_TYPES.get(ext, "application/octet-stream")


def to_c_name(filepath, base_dir):
    """Convert a file path to a valid C identifier."""
    rel = os.path.relpath(filepath, base_dir).replace("\\", "/")
    name = rel.replace("/", "_").replace(".", "_").replace("-", "_")
    return name


def compute_hash(www_dir):
    """Hash all web file contents + mtimes to detect changes."""
    h = hashlib.sha256()
    for root, _dirs, files in sorted(os.walk(www_dir)):
        for f in sorted(files):
            path = os.path.join(root, f)
            h.update(f.encode())
            h.update(str(os.path.getmtime(path)).encode())
            with open(path, "rb") as fh:
                h.update(fh.read())
    return h.hexdigest()


def needs_rebuild(www_dir, hash_file, output_header):
    """Check if the header needs regenerating."""
    if not os.path.exists(output_header):
        return True
    if not os.path.exists(hash_file):
        return True
    current = compute_hash(www_dir)
    try:
        with open(hash_file, "r") as f:
            stored = f.read().strip()
        return current != stored
    except Exception:
        return True


def generate_header(www_dir, output_header, hash_file):
    if not os.path.isdir(www_dir):
        print(f"[embed_webui] WARNING: {www_dir} not found, skipping")
        return

    if not needs_rebuild(www_dir, hash_file, output_header):
        print("[embed_webui] Web content unchanged, skipping generation")
        return

    files = []
    total_raw = 0
    total_gz = 0

    # Collect all files
    for root, _dirs, filenames in sorted(os.walk(www_dir)):
        for filename in sorted(filenames):
            filepath = os.path.join(root, filename)
            rel_path = os.path.relpath(filepath, www_dir).replace("\\", "/")
            uri = "/" + rel_path

            with open(filepath, "rb") as f:
                raw_data = f.read()

            gz_data = gzip.compress(raw_data, compresslevel=9)
            c_name = to_c_name(filepath, www_dir)
            mime = get_mime_type(filepath)

            files.append({
                "uri": uri,
                "c_name": c_name,
                "mime": mime,
                "raw_size": len(raw_data),
                "gz_data": gz_data,
                "gz_size": len(gz_data),
            })

            total_raw += len(raw_data)
            total_gz += len(gz_data)

    # Generate header
    lines = []
    lines.append("/**")
    lines.append(" * @file web_content.h")
    lines.append(" * @brief Auto-generated embedded web UI content (gzipped)")
    lines.append(" *")
    lines.append(" * DO NOT EDIT — generated by tools/embed_webui.py")
    lines.append(f" * Source: data/www/ ({len(files)} files, "
                 f"{total_raw} bytes raw, {total_gz} bytes gzipped)")
    lines.append(" */")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <pgmspace.h>")
    lines.append("#include <stddef.h>")
    lines.append("#include <stdint.h>")
    lines.append("")

    # Byte arrays
    for f in files:
        lines.append(f"// {f['uri']} ({f['raw_size']} bytes -> {f['gz_size']} bytes gzipped)")
        lines.append(f"static const uint8_t {f['c_name']}_gz[] PROGMEM = {{")
        data = f["gz_data"]
        for i in range(0, len(data), 16):
            chunk = data[i : i + 16]
            hex_str = ", ".join(f"0x{b:02x}" for b in chunk)
            lines.append(f"    {hex_str},")
        lines.append("};")
        lines.append(f"static const size_t {f['c_name']}_gz_len = {f['gz_size']};")
        lines.append("")

    # Lookup table
    lines.append("// Embedded file entry")
    lines.append("struct EmbeddedFile {")
    lines.append('    const char* uri;')
    lines.append('    const char* mimeType;')
    lines.append('    const uint8_t* data;')
    lines.append('    size_t length;')
    lines.append("};")
    lines.append("")
    lines.append(f"static const int EMBEDDED_FILE_COUNT = {len(files)};")
    lines.append("static const EmbeddedFile EMBEDDED_FILES[] = {")
    for f in files:
        lines.append(f'    {{"{f["uri"]}", "{f["mime"]}", '
                     f'{f["c_name"]}_gz, {f["c_name"]}_gz_len}},')
    lines.append("};")
    lines.append("")

    # Lookup function
    lines.append("/**")
    lines.append(" * Find an embedded file by URI path.")
    lines.append(" * @return Pointer to EmbeddedFile or nullptr if not found.")
    lines.append(" */")
    lines.append("static const EmbeddedFile* findEmbeddedFile(const char* uri) {")
    lines.append("    for (int i = 0; i < EMBEDDED_FILE_COUNT; i++) {")
    lines.append('        if (strcmp(uri, EMBEDDED_FILES[i].uri) == 0) {')
    lines.append("            return &EMBEDDED_FILES[i];")
    lines.append("        }")
    lines.append("    }")
    lines.append("    return nullptr;")
    lines.append("}")
    lines.append("")

    os.makedirs(os.path.dirname(output_header), exist_ok=True)
    with open(output_header, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    # Save hash
    os.makedirs(os.path.dirname(hash_file), exist_ok=True)
    with open(hash_file, "w") as f:
        f.write(compute_hash(www_dir))

    print(f"[embed_webui] Generated {output_header}")
    print(f"[embed_webui]   {len(files)} files, "
          f"{total_raw} bytes raw -> {total_gz} bytes gzipped")


generate_header(WWW_DIR, OUTPUT_HEADER, HASH_FILE)
