"""
PlatformIO pre-build script: auto-increment build number.

Reads a persistent build counter from .pio/build_number, increments it,
and generates include/build_info.h with the new BUILD_NUMBER define.

Usage in platformio.ini:
    extra_scripts = pre:tools/version_increment.py
"""

import os

Import("env")

BUILD_NUMBER_FILE = os.path.join(env.subst("$PROJECT_DIR"), ".pio", "build_number")
OUTPUT_HEADER = os.path.join(env.subst("$PROJECT_DIR"), "include", "build_info.h")


def increment_build_number():
    # Read current build number (or start at 0)
    build_number = 0
    if os.path.exists(BUILD_NUMBER_FILE):
        try:
            with open(BUILD_NUMBER_FILE, "r") as f:
                build_number = int(f.read().strip())
        except (ValueError, IOError):
            build_number = 0

    # Increment
    build_number += 1

    # Write back
    os.makedirs(os.path.dirname(BUILD_NUMBER_FILE), exist_ok=True)
    with open(BUILD_NUMBER_FILE, "w") as f:
        f.write(str(build_number))

    # Generate header
    os.makedirs(os.path.dirname(OUTPUT_HEADER), exist_ok=True)
    with open(OUTPUT_HEADER, "w", encoding="utf-8") as f:
        f.write("/**\n")
        f.write(" * @file build_info.h\n")
        f.write(" * @brief Auto-generated build number (DO NOT EDIT)\n")
        f.write(" *\n")
        f.write(" * Generated by tools/version_increment.py\n")
        f.write(" */\n")
        f.write("#pragma once\n")
        f.write("\n")
        f.write(f"#define BUILD_NUMBER {build_number}\n")

    print(f"[version] Build #{build_number}")


increment_build_number()
